version: '3'

volumes:
  banco:

services:
  app:
    depends_on:
      - db
    image: dsi2019gr:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DACS2019_DB_HOST=jdbc:mysql://db:3306/db_gr?useTimezone=true&serverTimezone=UTC
      - DACS2019_DB_USERNAME=bob
      - DACS2019_DB_PASSWORD=bob
  db:
    image: mariadb:10.3
    volumes:
      - banco:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_gr