version: '3'

volumes:
  banco:

services:
  db:
    image: mariadb:10.3
    volumes:
      - banco:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_gr